### ISSUE TITLE
Menu on demo page doesn't work

### ISSUE THREAD

**Issue by OllyHodgson** [alexanderlperez/headergrabbag#1]
When [the demo page](http://devbrainhack.co/projects/headergrabbag/) is narrow enough to show it, clicking the hamburger button toggles the button to become an "×" but does not show the menu.

Tested in Firefox 42 Nightly, IE11 and Chrome 45 Dev.

**Comment by alexanderlperez** [comment]
Thanks for the issue, but there's no actual pull-out menu, just bare fixed headers for people to style as they see fit. I've been thinking of adding that in the near future.
